server:
  port: 8081
spring:
  profiles:
    active: dev
---
server.port: 8080
spring:
  profiles: dev

debug: true
---
server.port: 8083
spring:
  profiles: prod
#userprofile:
#  userId: 1                     #    - e0
#  maps: { k1: v1 , k2: v2}      #    - e1
#  lists:
